### ISSUE TITLE
Devtools 🐛 store connects to redux devtools on each store subscription

### ISSUE THREAD

**Issue by GrzegorzKazana** [grzegorz-bielski/rxs#31]
Hi 👋 

**Describe the issue**
When using `@rxsv/tools` we `connect` to redux devtools on each `state$` subscription. This causes multiple store instances to show up in the devtools and chaotic switches between instances when multiple components subscribe/unsubscribe at the same time.

**Steps to reproduce**

1. Create store enhanced with `withDevtools`
2. Subscribe to `state$` more than once
3. Open devtools and open the dropdown allowing for selecting store instances - there will be as many instances as subscriptions to `state$`

**Potential fix**
I reckon the issue lays in `merge(store.state$, devToolsState$)`. 
`state$` is hot (by the virtue of `shareReplay` operator), but once we apply `merge` it becomes cold again. Therefore I think we just need to `shareReplay` the merged state.

Will open a PR with a test case soon.

**Comment by grzegorz-bielski** [comment]
The new version is available at [npm i @rxsv/tool@2.0.0-alpha.3](https://github.com/grzegorz-bielski/rxsv/releases/tag/v2.0.0-alpha.3)
