### ISSUE TITLE
Support for redux-devtools?

### ISSUE THREAD

**Issue by vicrac** [grzegorz-bielski/rxs#5]
According to [this article](https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f), it's possible to bind any custom (Redux-like) state management library to `redux-devtools` extension (you simply submit your actions and states via extension API). Will `rxsv` support that?

**Comment by grzegorz-bielski** [comment]
I was thinking about it for some time now, but recently I'm not using this library on a daily basis, so it went under the radar. 
I can't promise anything, but if I won't get distracted by some other stuff I am planning on tinkering with it.

**Comment by grzegorz-bielski** [comment]
@vicrac Done, the redux devtools support is available as of `1.2.0`, from the package on the public npm registry. 

More info here: https://github.com/grzegorz-bielski/rxsv/tree/master/packages/tools 
Let me know if there is anything that doesn't work properly. 

Closing this for now.
